# Mengubah kata singkatan menjadi kata aslinya
norm = {
     ' sepong ':' ',
     ' kontol ':' ',
     ' kontol':' ',
     'kontol ':' ',
     ' permenkontol ':' ',
     ' permen2kontol ':' ',
     ' anjingaturan ':' ',
     ' ngebacot2 ':' ',
     ' ngentot ':' ',
     'jncokkkk ':' ',
     ' jing ':' ',
     'tai ':' ',
     ' njing ':' ',
     ' njing':' ',
     ' anjing ':' ',
     ' njingg ':' ',
     'anj ':' ',
     ' anj ':' ',
     ' anj':' ',
     ' babi ':' ',
     ' bego ':' ',
     ' goblok ':' ',
     ' ngebacot ':' ',
     ' gbecus ':' ',
     ' anjj ':' ',
     ' permen2 ':' permen ',
     ' permen2heh ':' permen hai ',
     ' anjing!aturan ':' aturan ',
     ' berduitmikir goblok!':' berduit mikir ',
     ' gajikesejahteraan ':' gaji kesejahteraan',
     ' bru ':' baru ',
     ' iyaa ':' iya ',
     ' ya ':' iya ',
     ' yaa ':' iya ',
     ' cma ':' cuma ',
     ' jd ':' jadi ',
     ' pke ':' pakai ',
     ' jdian ':' jadian ',
     ' bcara ':' bicara ',
     ' dbaju ':' di baju ',
     ' bru ':' baru ',
     ' ksejahteraan ':'kesejahteraan',
     ' tp ':' tapi ',
     ' org ':' orang ',
     ' jugaa ':' juga ',
     ' hadeuh ':' haduh ',
     ' yg ':' yang ',
     ' ol ':' ',
     ' jg ':' juga ',
     ' uda ':' sudah ',
     ' udah ':' sudah ',
     ' dg ':' dengan ',
     ' sm ':' sama ',
     ' b ':' ',
     ' haloooo ':' halo ',
     ' njir ':' kaget ',
     ' kyk ':' seperti ',
     ' spt ':' seperti ',
     ' kek ':' seperti ',
     ' ehh ':' waduh ',
     ' gabutuh ':' tidak butuh ',
     ' ga ':' tidak ',
     ' ywdah ':' yaudah ',
     ' bocil ':' anak kecil ',
     ' tiati ':' hati hati ',
     ' skrg ':' sekarang ',
     ' naahh ': 'nah',
     ' rb ':' ribu ',
     ' bgt ':' banget ',
     ' gabang ':' tidak bang ',
     ' gw ':' saya ',
     ' gue ':' saya ',
     ' the ':' ke ',
     'the ':' ke ',
     ' power ':' kekuatan ',
     ' of ':' dari ',
     ' emak ':' ibu ',
     ' emak-emak ':' ibu ',
     ' trus ':' terus ',
     ' trs ':' terus ',
     ' trs':' terus ',
     ' agusyudhoyono ':' agus yudhoyono',
     ' pdemokrat ':' ',
     ' harisnya ':' harusnya ',
     ' ngeganti ':' ganti ',
     ' kalo ':' kalau ',
     ' klo ':' kalau ',
     ' jaman ':' zaman ',
     ' jaman':' zaman ',
     ' ih ':' kecewa ',
     'ih ':' kecewa ',
     ' krnapa ':' karena apa',
     ' karna ':' karena ',
     ' engga ':' enggan ',
     ' mrk ':' mereka ',
     ' ya ':' iya ',
     ' to':' iya ',
     ' karo ':' sama ',
     ' kui ':' itu ',
     ' akehan ':' banya ',
     ' upahe ':' gajinya ',
     ' ndeng':' tetapi ',
     ' gendeng ':' sedikit ',
     ' gituin ':' begitu ',
     ' el ':' ',
     ' keras ':' sulit ',
     ' robek ':' dipahami ',
     ' masmenteri ':' mas menteri',
     ' ortu ':'orang tua',
     ' gmn ':' gimana ',
     ' upgrade ':' meningkatkan',
     ' henryco ':' saya ',
     ' selesein ':' selesaikan ',
     ' goblok':' ',
     ' jdi2an ':' jadian ',
     ' lu ':' anda ',
     ' hmm ':' berfikir ',
     ' netes ':' menetas ',
     ' k ':' ribu ',
     ' engko ':' nanti ',
     ' berduitmikir ':' berduit mikir ',
     ' gajikesejahteraan/ ':' gaji kesejahteraan atau ',
     ' selesaikangaji ':' selesaikan gaji ',
     ' ancur ':' hancur ',
     ' atauguru ':' atau guru ',
     ' ttg ':' tentang ',
     ' up ':' naik ',
     ' date ':' tanggal ',
     ' guys ':' teman teman ',
     ' bs ':' bisa ',
     'ahy ':' ',
     'cok ':' ',
     ' = ':' sama dengan ',
     ' pecaat ':' pecat ',
     ' zonk':' tidak tercapai ',
     ' gk ':' tidak ',
     ' indonesaku':' indonesia ',
     ' next ':' selanjutnya ',
     ' bukaan ':' bukan ',
     ' komen2nya ':' komentarnya ',
     ' scroll ':' menelusuri ',
     ' owalah ':' aduh ',
     ' tenant ':' memang ',
     ' wkwkw ':' ',
     ' wkwk ':' ',
     ' kwkwkwkwkwk ':' ',
     ' wkwkwk':' ',
     ' wkwkwkwkqk ':' ',
     'wkwkwkwkqk ':' ',
     'hahaha ':' ',
     ' hahaha ':' ',
     ' akwkwkwk':' ',
     ' hhh':' ',
     ' wk':' ',
     ' awkwkwkwkward':' ',
     ' akwowkwok ':' ',
     ' laennya ':' lainnya ',
     ' cut ':' potong ',
     ' guru2 ':' guru-guru ',
     ' kmu ':' kamu ',
     ' yth ':' yang terhormat ',
     ' big applause ':' tepuk tangan meriah ',
     ' doank ':' doang ',
     ' thn ':' tahun ',
     ' ato ':' atau ',
     ' koar2 ':' berteriak ',
     ' buzzerp ':' orang bayaran ',
     ' sii ':' si ',
     ' noh ':' itu ',
     ' apasalahnya ':' apa salahnya ',
     ' sdh ':' sudah ',
     ' nggak ':' tidak ',
     ' lagi2 ':' lagi lagi ',
     ' what ':' apa ',
     ' do ':' yang ',
     ' you ':' kamu ',
     ' expect ':' harapkan ',
     ' tsb ':' tersebut ',
     ' realnya ':' realitanya ',
     ' satu2 ':' satu-satu ',
     ' bkn ':' bukan ',
     ' skrng ':' sekarang ',
     ' kira2 ':' kira kira ',
     ' backgroundnya ':' latar belakang',
     ' soft skill ':' keterampilan lunak',
     ' lbih ':' lebih ',
     ' jdi ':' jadi ',
     ' long ':' panjang ',
     ' ngeprint ':' mencetak ',
     ' (cont) ':' ',
     ' (cont)':' ',
     ' tetep ':' tetap ',
     ' hp ':' ponsel ',
     ' gimanaa ':' gimana ',
     ' yes ':' iya ',
     ' that is the point ':' itulah intinya ',
     ' td ':' tadi ',
     ' lihatt ':' lihat ',
     ' derassssssss ':' deras ',
     ' diliat2 ':' diliat liat ',
     ' acc ':' disetujui ',
     ' diangkat2 ':' diangkat angkat ',
     ' sgt ':' sangat ',
     ' ajah ':' aja ',
     ' krn ':' karena ',
     ' ak ':' aku ',
     ' btw ':' ngomong ngomong ',
     ' outsourcekan ':' alih daya ',
     ' outsourcing ':' alih daya ',
     ' sender ':' pengirim pesan ',
     ' hi ':' hai ',
     ' mpusss ':' kucing ',
     ' rp ':' rupiah ',
     ' leih ':' lebih ',
     ' lhah ':' lah ',
     ' jt ':' juta ',
     ' merjuangin ':' perjuangin ',
     ' gausa ':' tidak usah ',
     ' dsb ':' dan sebagainya ',
     ' yudhoyonodemokrat ': ' yudhoyono demokrat ',
     ' mibta ':' minta ',
     ' yudhoyonopdemokrat ':' yudhoyono demokrat ',
     ' better ':' lebih baik ',
     ' wb / ':' ',
     ' kementrian/lembaga ':' kementrian atau lembaga ',
     ' demokratdemokrat ':' demokrat ',
     ' (?) ':' ',
     ' sains ':' ilmu ',
     ' ja ':' aja ',
     ' tendik ':' trending ',
     ' tdk? ':' tidak ',
     ' ka ':' kakak ',
     ' miw ':' mau ',
     ' &amp ':' ',
     ' bukti² ':' bukti bukti ',
     ' holala ':' halo ',
     ' bg':' abang ',
     ' pura² ':' pura pura ',
     ' kicep ':' diam ',
     ' huh ':' kesal ',
     ' menunggutidak ':' menunggu tidak ',
     ' didapatkalo ':' didapat kalau ',
     ' tuk ':' untuk ',
     ' tengz ':' terimakasih ',
     ' putihh ':' putih ',
     ' ajh':' aja',
     ' polpolan ':' si ',
     ' wb ':' ',
     ' omahe ':' rumah ',
     ' burine ':' sebelah ',
     ' suhat ':' ',
     ' siji ':' satu ',
     ' iku ':' itu ',
     ' admine':' administrasinya ',
     ' apart ':' apartemen ',
     ' satusatusiji ':' satu ',
     ' co ':' cocok ',
     ' gin ':' begini ',
     ' gin':' begini ',
     ' tunggak ':' menunggak ',
     ' nahya ':' tanya ',
     ' apatenaga ':' aparatur negara ',
     ' oy ':' waduh ',
     ' freelance ':' pekerja lepas ',
     ' naek ':' naik ',
     'daaan ':' dan ',
     ' ngurus ':' mengurus ',
     ' dapetin ':' dapat ',
     ' ituuuu':' itu ',
     ' tentor ':' tentang ',
     ' privat ':' pribadi ',
     ' less ':' lebih sedikit ',
     ' action ':' tindakan ',
     ' x ':' kali ',
     ' cumaaa ':' cuma ',
     ' 25ribu ':' 25 ribu ',
     ' % ':' persen ',
     ' 20212023 ': ' 2021 sampai 2023 ',
     ' 100200rb ':' 100 sampai 200 ribu ',
     ' unfaedah ':' tidak berguna ',
     ' mennurunkan ':' menurunkan ',
     ' pingin ':' mau ',
     ' ganyi ':' ganti ',
     ' bolak ':' balik ',
     ' gituin':' begitu ',
     ' ppro ':' lebih ',
     ' nyangkut ':' tersangkut ',
     ' ywdah ':' baik ',
     ' maap ':' maaf ',
     ' vibrator ':' penggetar ',
     ' via ':' melalui ',
     ' 3t ':' 3 triliun',
     ' ddk':' dan kawan kawan ',
     ' sekolah2 ':' sekolah sekolah ',
     ' mreka ':' mereka ',
     ' pake ':' pakai ',
     ' mengsedih ':' sedih ',
     ' more people':' banyak orang',
     ' in the game ':' dalam permainan ',
     ' more mard ':' semakin sulit ',
     ' cuannya ':' uangnya ',
     ' cuannya':' uangnya ',
     ' yrs ':' tahun ',
     ' gtgt ':' begitu ',
     ' gt ':' begitu ',
     ' beuh ':' kaget ',
     ' stand for them ':' berdiri untuk mereka ',
     ' gw':' saya ',
     ' kl ':' kalau ',
     ' rk ':' mereka ',
     ' ndompleng ':' mengikuti ',
     ' stress ':' stres ',
     ' ilang ':' hilang ',
     ' loe ':' anda ',
     ' lol ':' ',
     ' bgst ':' ',
     ' nadik ':' nadiem ',
     ' owi ':' jokowi ',
     ' part ':' bagian ',
     ' sblmnya ':' sebelum',
     ' peace':' damai ',
     'singapour':'singapura',
     ' km ':' kamu ',
     'belakangbukan ':' belakang bukan ',
     ' gausah ':' tidak usah',
     ' mainmain ':' main main ',
     ' leb ':' lebih ',
     ' + ':' tambah ',
     ' gabang':' tidak bang ',
     ' sdsma':' sd sampai sma',
     ' tiba2 ':' tiba tiba ',
     ' ehh ':' eh ',
     'ehh ':' eh ',
     'nahiya ':' nah iya',
     ' kurang(':' kurang ',
     ' () ':' ',
     ' 400600k ':' 400 sampai 600 ribu ',
     ' nder ':' anda ',
     ' dok ':' dokter ',
     ' dek ':' kamu ',
     'tenant ':' benar ',
     ' dll ':' dan lain lain ',
     ' (udah kerja puluhan tahun) ':' sudah kerja puluhan tahun ',
     ' umk/umr':' umk atau umr ',
     ' (kurng tau dilanjutin pak pj gk)':' kurang tau selanjutnya pak perpanjang tidak ',
     ' cmiiw ':' koreksi jika saya salah ',
     ' anak²nya ':' anak anak nya ',
     ' btuh ':' butuh ',
     ' sbyk ':' sebanyak ',
     ' byk ':' banyak ',
     ' jga ':' juga ',
     ' st ':' situ ',
     ' n ':' nih ',
     ' e ':' nya ',
     ' (g)emas ':' emas ',
     ' nunggunga':' menunggu ',
     ' uangnha ':' uangnya ',
     ' lift ':' angkat ',
     ' lol':' ',
     ' negaranegara ':' negara negara ',
     'leb ':' lebih ',
     ' leb':' lebih ',
     ' sebelumpeduli ':' sebelum peduli ',
     ' bro ':' kawan ',
     ' knp ':' kenapa ',
     ' (honorer) ':' honorer ',
     ' oprec ':' Rekrutmen terbuka ',
     ' hp':' ponsel ',
     ' lihatt':' lihat ',
     'gur ':' guru ',
     ' gur ':' guru ',
     ' riburibu ':' ribu ',
     ' le ':' kawan ',
     ' anak2 ':' anak anak ',
     ' gara2 ':' gara gara ',
     ' malas2an ':' malas malasan ',
     ' dgn ':' dengan ',
     ' udh ':' udah ',
     ' pd ':' pada ',
     ' tdk ':' tidak ',
     ' al ':' alih ',
     ' hbs ':' habis ',
     ' full ':' penuh ',
     ' first ':' pertama',
     ' step ':' langkah ',
     ' in ':' dalam ',
     ' meritocracy ':' meritokrasi ',
     ' clearin ':' dibersihkan ',
     ' core ':' inti ',
     ' business ':' bisnis ',
     ' step ':' langkah ',
     ' guu ':' guru ',
     ' sdsd ':' sd ',
     ' begtulah ':' begitulah ',
     ' luarbiasa ':' luar biasa ',
     ' honorer+tetek ':' honorer dan tetek ',
     ' ngas ':' masih ',
     '(( ':' ',
     ' (( ':' ',
     ' ((':' ',
     ' ekonomidari ':' ekonomi dari ',
     ' cita cita ':' cita cita ',
     ' zumaexcel ':' ',
     ' [cm]':' cuma ',
     ' (ppg) ':' ppg ',
     ' kw ':' palsu ',
     ' berhasilketagihan ':' berhasil ketagihan ',
     ' lagiphp ':' lagi harapan palsu ',
     ' 1pgri ':' satu pgri ',
     ' 2di ':' 2 di ',
     ' 3mobil ':' 3 mobil ',
     ' 4bansos ':' 4 bansos ',
     ' 5ekonomi ':' 5 ekonomi ',
     ' 6di ':' 6 di ',
     ' go ':' tingkat ',
     ' iol ':' ',
     ' org2 ':' orang orang ',
     ' orgnya ':' orangnya ',
     ' d ':' di ',
     ' (kecuali materai) ':' kecuali materai ',
     ' education ':' edukasi ',
     ' ngecut ':' dipotong ',
     ' chance ':' kesempatan ',
     'au ':' tau ',
     ' mg ':' memang ',
     ' ww ':' ',
     ' tt ':' ',
     ' gua ':' saya ',
     ' ulangpun ':' ulang pun ',
     ' bjir':' ',
     ' ujungpelosok ':' ujung pelosok ',
     ' itungitungan ':' hitung hitungan ',
     ' gedhe ':' gede ',
     ' (masalah sebutan saja) ':' masalah sebut saja ',
     ' kemanamana ':' kemana mana ',
     ' secuprit upil ': ' kecil ',
     'fyi ':' sebagai informasi ',
     'terserahyg ':' terserah yang ',
     ' aneh2 ':' aneh aneh ',
     ' jgn ':' jangan ',
     ' murid665 ':' murid ',
     ' tal ':' tapi ',
     ' guru/kep sek ':' guru atau kepsek ',
     ' tpi ':' tapi ',
     ' honorer/bawahannya ':' honorer atau bawahannya ',
     'gakkk ':' tidak ',
     ' doing ':' melakukan ',
     ' anything ':' apapun ',
     ' but ':' kecuali ',
     ' properly':' dengan baik ',
     ' single ':' lajang ',
     ' pas2an ':' pas pasan ',
     ' samaorang ':' sama orang ',
     ' tuajuga ':' tua juga ',
     'gmn2 ':' gimana gimana',
     'mung ':' hanya ',
     ' (katanya bamper sosial) ':' katanya bamper sosial ',
     ' (buat bantu para honorer yang kalau dipikir lagi bukankah ada yang leb kecewa wajib memberikan honor)': ' buat bantu para honorer yang kalau dipikir lagi bukankah ada yang leb kecewa wajib memberikan honor ',
     ' leb ':' lebih ',
     'nek ':' jika ',
     ' awakmu ':' anda ',
     ' nde ':' tidak ',
     ' gowoean ':' bersenda gurau ',
     ' ae ':' saja ',
     ' wong ':' orang ',
     ' sek ':' sekadar ',
     ' kind ':' jenis ',
     ' convo ':' percakapan ',
     ' like ':' suka ',
     ' so ':' sangat ',
     ' much ':' saya ',
     ' cidek ':' tidak ',
     ' kepo ':' tahu ',
     ' statement ':' pernyataan ',
     ' elek ':' lainnya ',
     ' another ':' alasan lainnya ',
     ' reason ':' alasan ',
     ' rekan2 ':' rekan rekan ',
     ' rese ':' resek ',
     ' mood ':' suasana hati ',
     ' guh ':' duh ',
     ' lho ':' loh ',
     'getu ':' gitu ',
     ' sekolah/ponpes ':' sekolah atau ponpes ',
     ' bagus2nya ':' bagus bagusnya ',
     ' msk ':' masuk ',
     ' univ ':' universitas ',
     ' negri ':' negeri ',
     ' lg ':' lagi ',
     ' hny ':' hanya ',
     ' sragam ':' seragam ',
     ' what':' apa ',
     ' dpt ':' dapat ',
     ' blom ':' belum ',
     ' difambah ':' ditambah ',
     ' cape2 ':' cape-cape ',
     ' (ikn) ':' ikn ',
     ' indo ':' indonesia ',
     'gbisa ':' tidak bisa ',
     ' gaaa':' tidak ',
     ' mw ':' mau ',
     ' maw':' mau ',
     ' ce ess ':' teman ',
     ' adekadek ':' adik adik ',
     ' please ':' tolong ',
     ' permanensukuwan ':' permanen sukuran ',
     ' ga':' tidak ',
     ' lgsg ':' langsung ',
     ' ngga':' tidak ',
     ' sg ':' sangat ',
     ' ngehate ':' benci ',
     ' koyok ':' seperti ',
     ' lek ':' itu ',
     ' ae ':' saja ',
     ' yo ':' ya ',
     ' summary ':' ringkasan ',
     ' nggae ':' buat ',
     ' translate ':' terjemahan ',
     ' mbok ':' mungkin ',
     ' kiro ':' berapa ',
     ' opo ':' apa ',
     'opoo ':' apa ',
     ' uwong ':' orang ',
     ' guduk ':' pondok ',
     ' herannn':' heran ',
     'uelek ':' jelek ',
     ' base ':' basis ',
     'bisabisanya ':' bisa bisanya ',
     ' compare ':' membandingkan ',
     ' meningkatkandiri ':' meningkatkan diri ',
     ' nder ':' ini orang ',
     ' kon ':' kondisi ',
     ' a ':' apa ',
     ' timbangane ':' mempertimbangkan ',
     ' ngeneki ':' begitu ',
     ' golek ':' cari ',
     ' carane ':' caranya ',
     ' shine ':' bersinar ',
     ' dewe ':' sendiri ',
     ' ae ':' saja ',
     'bisa2 ':' bisa bisanya ',
     ' fail':' gagal ',
     ' pinterpinter ':' pintar pintar ',
     ' suram/ngeness ':' suram atau ngenes ',
     ' temenannn ':' teman saya ',
     ' cen ':' sedang ',
     'bully ':' penindas ',
     ' dimana2 ':' dimana mana ',
     'random ':' acak ',
     ' pipel ':' orang ',
     'org ':' orang ',
     ' pgn':' mau ',
     '  rombak2 ':' rombak rombak ',
     ' crusial ':' sangat penting ',
     ' msh ':' masih ',
     ' lbh ':' lebih ',
     'kasihaaan ':' kasihan ',
     ' i':'saya ',
     ' jugasaya ':' juga saya ',
     ' sayamereka ':' saya mereka ',
     ' wajarga ':' wajar tidak ',
     ' endorse ':' promosi ',
     ' prilkaka ':' pikiran ',
     ' n ':' ',
     ' owyeahh ':' oh ',
     ' lebi ':' lebih ',
     ' lg ':' lagi ',
     'manok ':' yang ',
     ' mestii ':' dilakukan ',
     'gaiso ':' tidak bisa ',
     ' murup ':' menyala ',
     'mosok ':' masa ',
     ' ta ':' itu ',
     ' digae ':' dibuat ',
     ' wallpaper':' latar layar ',
     'podo ':' sama ',
     ' ben ':' agar ',
     ' epribade':' semuanya ',
     'inilaah ':' inilah ',
     ' spy ':' supaya ',
     ' saatdaftar ':' saat daftar ',
     ' blom ':' belum ',
     'huhuu ':' sedih ',
     ' move ':' pindah ',
     ' krna ':' karena ',
     ' kutunggu ':' aku tunggu ',
     ' ky ':' kok ',
     'nak ':' anak ',
     ' dalan ':' jalan ',
     ' bertahun2 ':' bertahun tahun ',
     ' smpe ':' sampai ',
     ' njirr':' ',
}

def normalisasi(str_text):
     for i in norm:
          str_text = str_text.replace(i, norm[i])
     return str_text