# import re

# # Dictionary of replacements
# replacements = {'krn': 'karena',
#                 'blm': 'belom',
#                 'hrs': 'harus',
#                 'bkn': 'bukan',
#                 'yg': 'yang',
#                 'ny': 'ya',
#                 'dr': 'dari',
#                 'jd': 'jadi',
#                 'bsbs': 'bisa',
#                 'mrk': 'mereka',
#                 'msh': 'masih',
#                 'hrsnya': 'harusnya',
#                 'sdngkan': 'sedangkan',
#                 'lu': 'kamu',
#                 'loe': 'kamu',
#                 'lo': 'kamu',
#                 'gw': 'aku',
#                 'bgt': 'banget',
#                 'byr': 'bayar',
#                 'thn': 'tahun',
#                 'boro²': 'boro-boro',
#                 'hehe': 'tertawa',
#                 'pdhl': 'padahal',
#                 'semangatt':'semangat',
#                 'bpk': 'bapak',
#                 'tp': 'tapi',
#                 'aje': 'aja',
#                 'ngabis2in': 'ngabisin',
#                 'indo': 'indonesia',
#                 'ngga': 'tidak',
#                 'nggak': 'tidak',
#                 'rp500': 'rupiah 500',
#                 'gmn': 'gimana',
#                 'nyuri2': 'mencuri',
#                 '1th': '1 tahun',
#                 '2jt': '2 juta',
#                 'kyk':' kaya',
#                 'kalo': 'kalau',
#                 'gaada': 'tidak ada',
#                 'yaallah': 'ya allah',
#                 '15jt': '15 juta',
#                 'tuk': 'untuk',
#                 '300k': '300 ribu',
#                 'tu': 'itu',
#                 'pgnnya': 'pengenya',
#                 '50k': '50 ribu',
#                 'ga': 'tidak',
#                 'gk': 'tidak',
#                 'murid2': 'murid-murid',
#                 'bjirr': '',
#                 'klo': 'kalau',
#                 'dgn': 'dengan',
#                 'yaaa': 'ya',
#                 'tmn': 'teman',
#                 '100k': '100 ribu',
#                 '600k': '600 ribu',
#                 'skrg': 'sekarang',
#                 'udh': 'sudah',
#                 'bnr': 'benar',
#                 'yaa': 'ya',
#                 'klao': 'kalau',
#                 'ganyampe': 'tidak sampai',
#                 'mamak': 'ibu',
#                 'nggk': 'tidak',
#                 '300rb': '300 ribu',
#                 'bener2': 'benar-benar',
#                 'klw': ' kalau',
#                 'kl': 'kalau',
#                 'wkwk':' tertawa',
#                 'jgn': 'jangan',
#                 'setiap-': 'setiap',
#                 'wkwkw': 'tertawa',
#                 '100ribu': '100 ribu',
#                 'jjur': 'jujur',
#                 'it': 'itu',
#                 'dpe': 'dapat',
#                 'skolah': 'sekolah',
#                 'dptnya': 'dapatnya',
#                 'ssuai': 'sesuai',
#                 'lbih': 'lebih',
#                 'tptnya': 'tepatnya',
#                 'dg': 'dengan',
#                 'rata2': 'rata-rata',
#                 '1jt': '1 juta',
#                 '800rb': '800 ribu',
#                 '600rb': '600 ribu',
#                 'samaratakan': 'sama rata',
#                 '500-1jt': '500 sampai 1 juta',
#                 'gue': 'aku',
#                 'trs': 'terus',
#                 'rata²': 'rata-rata',
#                 'maap': 'maaf',
#                 'emg': 'emang',
#                 'polll': 'banget',
#                 'trus': 'terus',
#                 'byk': 'banyak',
#                 '2th': '2 tahun',
#                 'ketidakadilam': 'tidak adil',
#                 'tmen': 'teman',
#                 'jg': 'juga',
#                 'bengsin': 'bensin',
#                 'knapa': 'kenapa',
#                 'njirrrr': '',
#                 'gata': 'gatau',
#                 'dll': 'dan lain-lain',
#                 'ekekek': 'tertawa',
#                 'splitbill': 'split bill',
#                 'km': 'kamu',
#                 'bjrot': '',
#                 'gadibayar': 'tidak dibayar',
#                 'pns/p3k': 'pns atau p3k',
#                 'pokoktpg': 'pokok tpg',
#                 'dikantorob': 'dikantor ob',
#                 '6jt': '6 juta',
#                 '5jt': '5 juta',
#                 '200k': '200 ribu',
#                 'aj': 'aja',
#                 'sm': 'sama',
#                 'gj': 'gaji',
#                 'ngr': 'negara',
#                 'yaaaa': 'ya',
#                 '100k/bulan': '100 ribu per bulan',
#                 '150k': '150 ribu',
#                 'kontrak/tdk': 'kotrak atau tidak',
#                 'skrng': 'sekarang',
#                 'bnyk': 'banyak',
#                 'dibanding2in': 'dibanding-banding',
#                 'buruh2': 'buruh-buruh',
#                 'prcuma': 'percuma',
#                 'w': '',
#                 'g': '',
#                 'jdi': 'jadi',
#                 'mak': 'ibu',
#                 '300-800rb/bln': '300 sampai 800 ribu per bulan',
#                 'emng': 'emang',
#                 'swasta2': 'swasta-swasta',
#                 'jt': 'juta',
#                 '800k': '800 ribu',
#                 'dsb': 'dan sebagainya',
#                 '6jam': '6 jam',
#                 '60k': '60 ribu',
#                 '500rb': '500 ribu',
#                 'maknya': 'makanya',
#                 'cma': 'cuma',
#                 'wkwkwk': 'tertawa',
#                 'krna': 'karena',
#                 'poll': 'banget',
#                 'engga': 'tidak',
#                 'apalgi': 'apa lagi',
#                 'sekolah2': 'sekolah-sekolah',
#                 'guru2': 'guru-guru',
#                 '3bulan': '3 bulan',
#                 'berbulan2': 'berbulan-bulan',
#                 'gausah': 'tidak usah',
#                 'orang2': 'orang-orang',
#                 'sj': 'saja',
#                 'sy': 'saya',
#                 'bs': 'bisa',
#                 'dpt': 'dapat',
#                 'mmang': 'memang',
#                 'plg': 'paling',
#                 'rb': 'ribu',
#                 'bln': 'bulan',
#                 'dpt': 'dapat',
#                 'org': 'orang',
#                 'njir': '',
#                 'buanyakkk': 'banyak',
#                 '250k': '250 ribu',
#                 'jtan': 'jutaan',
#                 'bpk/ibu': 'bapak ibu',
#                 'bhkan': 'bahkan',
#                 '300rb/bulan': '300 ribu per bulan',
#                 'riil': 'real',
#                 '500-800k': '500-800 ribu',
#                 '50-100k': '50-100 ribu',
#                 'd': 'di',
#                 'pnsskrng': 'pns sekarang',
#                 'ngk': 'tidak',
#                 '12th': '12 tahun',
#                 '8jt': '8 juta',
#                 'sertivikasi': 'sertifikasi',
#                 'apalagi': 'apa lagi',
#                 '400k/3bln ': '400 per 3 bulan',
#                 'dh': 'sudah',
#                 'adany': 'adanya',
#                 'brp': 'berapa',
#                 'nderr': 'nder',
#                 'jgnkan': 'jangankan',
#                 'geede': 'gede',
#                 'gajitunjangannya': 'gaji tunjangannya',
#                 'ibun': 'ibu',
#                 'dpet': 'dapat',
#                 'ketrimanya': 'keterimanya',
#                 'taun': 'tahun',
#                 '500k': '500 ribu',
#                 'mommy': 'mother',
#                 '1jt/bulan': '1 juta per bulan',
#                 'bhs': 'bahasa',
#                 'th': 'tahun',
#                 '8rb': '8 ribu',
#                 '200rban': '200 ribuan',
#                 'lbh': 'lebih',
#                 'dri': 'dari',
#                 '2jutaan': '2 jutaan',
#                 'stafsus2': 'staf khusus',
#                 'gt': 'gitu',
#                 'knp': 'kenapa',
#                 '200-300k': '200 sampai 300 ribu',
#                 'dlu': 'dulu',
#                 'aolg': '',
#                 'skolah2': 'sekolah-sekolah',
#                 'bjir': '',
#                 '700/800/bln': '700 sampai 800 bulan',
#                 'temen2': 'teman-teman',
#                 'cukup2': 'cukup-cukup',
#                 'sihhh': 'sih',
#                 'jtaan': 'jutaan',
#                 'oon': '',
#                 'itutuh': 'itu',
#                 'smpe': 'sampai',
#                 'sekali2': 'sekali-sekali',
#                 'nyap2': 'sapa-sapa',
#                 'jir': '',
#                 'liat2': 'liat-liat',
#                 'kemarin2': 'kemarin-kemarin',
#                 'bisa2': 'bisa-bisa',
#                 'lg': 'lagi',
#                 'sgt': 'sangat',
#                 'wlp': 'walaupun',
#                 'twit': 'tweet',
#                 'guru²': 'guru-guru',
#                 'cm': 'cuma',
#                 'ma': 'sama',
#                 'plosok': 'pelosok',
#                 'kcil': 'kecil',
#                 'mrk2': 'mereka-mereka',
#                 'n': '',
#                 'bwt': 'buat',
#                 'murid2nya': 'muridnya',
#                 'kbnykn': 'kebanyakan',
#                 'ckp': 'cukup',
#                 'fokusny': 'fokusnya',
#                 'srtifikasi': 'sertifikasi',
#                 'sminar': 'seminar',
#                 'pnting': 'penting',
#                 'ja': 'aja',
#                 'gada': 'tidak ada',
#                 'guru²': 'guru-guru',
#                 'liet': 'liat',
#                 'orang²': 'orang-orang',
#                 'lunya': 'kamunya',
#                 'ko': 'kok',
#                 'krponakan': 'keponakan',
#                 'gajitunjangan': 'gaji tunjangan',
#                 'anying': '',
#                 'wkkwkwkw': '',
#                 '700k': '700 ribu',
#                 'pemerintah2': 'pemerintah-pemerintah',
#                 'guru²': 'guru-guru',
#                 'sik': 'si',
#                 'kota2': 'kota-kota',
#                 '500ish': '500 ih',
#                 'sgt': 'sangat',
#                 'lg': 'lagi',
#                 'manaaa': 'mana',
#                 'pny': 'punya',
#                 'noh': 'itu',
#                 'rebu': 'ribu',
#                 '3jtan': '3 jutaan',
#                 '5jtan': '5 jutaan',
#                 'buzzerp': 'buzzer',
#                 'goblok': '',
#                 'duduk2': 'duduk-duduk',
#                 'staff': 'staf',
#                 'gajiii': 'gaji',
#                 'tdk': 'tidak',
#                 'betullll': 'betul',
#                 'aplg': 'apa lagi',
#                 'ttp': 'tetap',
#                 'daridulu': 'dari dulu',
#                 'masalag': 'masalah',
#                 '3jt': '3 juta',
#                 'bwah':'bawah',
#                 'jkw': 'jokowi',
#                 '3jt-': '3 juta',
#                 'utk': 'untuk',
#                 'politiksementara': 'politik sementara',
#                 '450rb': '450 ribu',
#                 'mirisss': 'miris',
#                 '25ribu': '25 ribu',
#                 'jml': 'jumlah',
#                 'rp1500000': 'rupiah 1500000',
#                 'rp2000000': 'rupiah 2000000',
#                 'rp300000': 'rupiah 300000',
#                 'rp1000000': 'rupiah 1000000',
#                 'kek': 'kaya',
#                 'mlm': 'malam',
#                 'ap': 'apa',
#                 'bajingan': '',
#                 'woii': 'teriak',
#                 'honorerrr': 'honorer',
#                 'baru2': 'baru-baru',
#                 'manusiawimenuju': 'manusiawi menuju',
#                 'gila2an': 'gila-gilaan',
#                 'honorerviralin': 'honorer viralin',
#                 'dtg': 'datang',
#                 '20-30jt': '20 sampai 30 juta',
#                 'é déwé': 'dewe',
#                 'aq': 'aku',
#                 'wkt': 'waktu',
#                 'sdgkan': 'sedangkan',
#                 'tsb': 'tersebut',
#                 'unt': 'untuk',
#                 'trima': 'terima',
#                 'nyahmmmm': 'nya',
#                 'cari2': 'cari-cari',
#                 'bosssqq': 'bos',
#                 'gwe': 'aku',
#                 'brhrp': 'berharap',
#                 'y': 'ya',
#                 'boss': 'bos',
#                 'parttime': 'part time',
#                 'kbutuhan': 'kebutuhan',
#                 'sndiri': 'sendiri',
#                 'sihh': 'sih',
#                 'ma': 'sama',
#                 'leus': 'lexus',
#                 'ug': 'juga',
#                 'jadio': 'jadi',
#                 'rebu': 'ribu',
#                 'sama2': 'sama-sama',
#                 '200-300rb': '200 sampai 300 ribu',
#                 'tolonh': 'tolong',
#                 'donk': 'dong',
#                 'pmrintah': 'pemerintah',
#                 'blum': 'belum',
#                 'mo': 'mau',
#                 'tsnyw': 'tsnya',
#                 'embel2': 'embel-embel',
#                 'honorerengga': 'honorer enggan',
#                 'pokoktunjangan': 'pokok tunjangan',
#                 '4jt': '4 juta',
#                 'stlh': 'setelah',
#                 'tmbahan': 'tambahan',
#                 'oiyah': 'oh iya',
#                 '3jt': '3 juta',
#                 'sehari²': 'sehari-hari',
#                 'vidronya': 'videonya',
#                 'bapa': 'bapak',
#                 'ape': 'apa',
#                 'mongkin': 'mungkin',
#                 'ndiri': 'sendiri',
#                 'gapake': 'tidak pakai',
#                 'yanggede': 'yang gede',
#                 'klu': 'kalau',
#                 'lgi': 'lagi',
#                 'woooy': 'teriak',
#                 'sngt': 'sangat',
#                 'iiia': 'ia',
#                 'rb/bulan': 'ribu per bulan',
#                 'main2': 'main-main',
#                 'manaaa': 'mana',
#                 'gedeee': 'gede',
#                 'gua': 'aku',
#                 'haaa': 'ha',
#                 'ape': 'apa',
#                 'mmg': 'memang',
#                 'pinjolpertama': 'pinjol pertama',
#                 '20ribu': '20 ribu',
#                 '250rebu': '250 ribu',
#                 'hahahahha': 'tertawa',
#                 'gamau': 'tidak mau',
#                 'idup': 'hidup',
#                 '6bln': '6 bulan',
#                 '3bln': '3 bulan',
#                 'skr': 'sekarang',
#                 'hey':'hai',
#                 '200-an': '200 an',
#                 'iyaa': 'iya',
#                 'tetep': 'tetap',
#                 'nyimbang': 'sumbang',
#                 'nder': 'sender',
#                 'deket': 'dekat',
#                 'gtu': 'gitu',
#                 'ckup': 'cukup',
#                 'kuli': 'kuliah',
#                 'dongg': 'dong',
#                 'temen': 'teman',
#                 'bhw': 'bahwa',
#                 'ortu': 'orang tua',
#                 'orgtua': 'orang tua',
#                 'gengss': 'geng',
#                 'sbrapa': 'seberapa',
#                 'sattt': '',
#                 'gtu': 'gitu',
#                 'kdd': 'kadang',
#                 'kd': 'kadang',
#                 'tpi': 'tapi',
#                 'susahada': 'susah ada',
#                 'blio': 'beliau',
#                 'surih': 'suruh',
#                 'yak': 'ya',
#                 'udeh': 'udah',
#                 '44jt': '44 juta',
#                 '150rb': '150 ribu',
#                 'rp20': 'rupiah 20',
#                 'sbg': 'sebagai',
#                 'alloh': 'allah',
#                 '44jt8': '44 juta 8',
#                 '352jt': '352 juta',
#                 'gweh': 'aku',
#                 '19th': '19 tahun',
#                 'mauuuu': 'mau',
#                 'ajg': '',
#                 'awowkwk': 'tertawa',
#                 'beuhh': 'aduh',
#                 'ironic': 'ironi',
#                 'skitaran': 'sekitaran',
#                 'bln': 'bulan',
#                 'rata2': 'rata-rata',
#                 '8jm': '8 jam',
#                 'hr': 'hari',
#                 'anjggg': '',
#                 'anjirrr': '',
#                 'cmn': 'cuma',
#                 '200rb': '200 ribu',
#                 '500rb': '500 ribu',
#                 'mggu': 'minggu',
#                 'mumet2': 'mumet-mumet',
#                 'tpi': 'tapi',
#                 'yaampun': 'ya ampun',
#                 '2-4jt': '2 sampai 4 juta',
#                 'rmh': 'rumah',
#                 'gedong': 'gedung',
#                 'brngkt': 'berangkat',
#                 'krja': 'kerja',
#                 'sragam': 'seragam',
#                 'sbnrnya': 'sebenarnya',
#                 'bjirrrr': '',
#                 '400rb': '400 ribu',
#                 'dlm': 'dalam',
#                 'dl': 'dulu',
#                 'ujung2nya': 'ujungnya',
#                 'ntu': 'itu',
#                 '160juta': '160 juta',
#                 '300k': '300 ribu',
#                 'kepsek': 'kepala sosial',
#                 'apasih': 'apa sih',
#                 'coy': 'teman',
#                 'listrikair': 'listrik air',
#                 '170rb': '170 ribu',
#                 '348rb': '348 ribu',
#                 '10kg': '10 kilo',
#                 'sehari2': 'sehari-hari',
#                 'bbrp': 'beberapa',
#                 'anu': 'itu',
#                 'cwe': 'wanita',
#                 'anjirr': '',
#                 'prndapat': 'pendapat',
#                 'bjirrr': '',
#                 'kudu': 'harus',
#                 '8juta': '8 juta',
#                 'heheh': 'tertawa',
#                 'heheheh': 'tertawa',
#                 '250-400k': '250 sampai 400 ribu',
#                 'wkkwkw': 'tertawa',
#                 'ka': 'kakak',
#                 '500rban': '500 ribuan',
#                 '38jt': '38 juta',
#                 '48k': '48 ribu',
#                 'okok': 'oke',
#                 'ok': 'oke',
#                 '24jt': '24 juta',
#                 'ngehe': '',
#                 'l': '',
#                 'susaaaaah': 'susah',
#                 '600rb': '600 ribu',
#                 'gatau': 'gak tahu',
#                 '800ribu': '800 ribu',
#                 'pd': 'pada',
#                 'enak2': 'enak-enak',
#                 'gapapa': 'tidak apa',
#                 'awokwokwok': 'tertawa',
#                 'baik2': 'baik-baik',
#                 'trmsuk': 'termasuk',
#                 'kdg': 'kadang',
#                 'mskipun': 'meskipun',
#                 'kdng': 'kadang',
#                 'dikityang': 'dikit yang',
#                 'dech': 'deh',
#                 'ver': 'ber',
#                 'rb': 'ribu',
#                 'jp': 'jam pelajaran',
#                 'kkak': 'kakak',
#                 'pdhal': 'padahal',
#                 'leha2': 'leha-leha',
#                 'hari2': 'hari-hari',
#                 'ky': 'kaya',
#                 'brooh': 'teman',
#                 '500k': '500 ribu',
#                 'samsek': 'sama sekali',
#                 'abcde': '',
#                 'bareng2': 'bareng-bareng',
#                 'nakes2': 'nakes-nakes',
#                 'beda2': 'beda-beda',
#                 'mirip2': 'mirip-mirip',
#                 'org2': 'orang-orang',
#                 'msii': 'misi',
#                 'shat': 'sehat',
#                 'sdah': 'sudah',
#                 'padti': 'pasti',
#                 'ks': 'kasih',
#                 'nnti': 'nanti',
#                 'coy': 'teman',
#                 'duh': 'aduh',
#                 'pakkkk': 'pak',
#                 'ktmu': 'ketemu',
#                 'ashdjdklsla': '',
#                 'sehari2': 'sehari-hari',
#                 '600khibah': '600 khibah',
#                 '1kalo': '1 kalau',
#                 '2kalau': '2 kalau',
#                 'sklh': 'sekolah',
#                 'sklah': 'sekolah',
#                 'jrg': 'jarang',
#                 'ntar': 'nanti',
#                 'skali': 'sekali',
#                 'bgitu': 'begitu',
#                 'kyapa': 'kaya apa',
#                 'soh': 'sih',
#                 'qt': 'kita',
#                 'bacot': '',
#                 'pmdapat': 'pendapat',
#                 'mlhat': 'melihat',
#                 'mmng': 'memang',
#                 'hal2': 'hal-hal',
#                 'mmbuat': 'membuat',
#                 'salah2in': 'salahin',
#                 'ehh': 'eh',
#                 'nuih': 'nih',
#                 'kampung2': 'kampung-kampung',
#                 'mw': 'mau',
#                 '25jt': '25 juta',
#                 'anak2nya': 'anaknya',
#                 '400-600rb': '400 sampai 600 ribu',
#                 '300rb-1jt': '300 sampai 1 juta',
#                 'tmpt': 'tempat',
#                 'hahah': 'tertawa',
#                 'jkt': 'jakarta',
#                 'berpuluh2': 'berpuluh-puluh',
#                 '300rebu': '300 ribu',
#                 'sbgian': 'sebagian',
#                 '1usd16rb': '1 dollar 16 ribu',
#                 'tdl': 'tidak',
#                 'bbrp': 'beberapa',
#                 'kecil2': 'kecil-kecil',
#                 'hadeuh': 'haduh',
#                 'sepong': '',
#                 'jdi2an': 'jadian',
#                 'bru': 'baru',
#                 'pke': 'pakai',
#                 'ngebacot2': '',
#                 'permen2kontol': '',
#                 'permen2heh': 'permen hai',
#                 'jing': '',
#                 'bcara': 'bicara',
#                 'permen2': 'manis-manis',
#                 'ngentot': '',
#                 'dbaju': 'di baju',
#                 'selesein': 'selesaikan',
#                 'ksejahteraan': 'kesejahteraan',
#                 'gbecus': 'tidak becus',
#                 'anjingaturan': 'aturan',
#                 'berduitmikir': 'berduit mikir',
#                 'naek': 'naik',
#                 'laennya': 'lainnya',
#                 'yth': 'yang terhormat',
#                 'ehh': 'eh',
#                 'kmu': 'kamu',
#                 'dkk': 'dan kawan kawan',
#                 'kputsn': 'keputusan',
#                 'btuh': 'butuh',
#                 'sbyk': 'sebanyak',
#                 'jga': 'juga',
#                 'owi': 'jokowi',
#                 'macet2': 'macet-macet',
#                 'bagi2': 'bagi-bagi',
#                 'e': '',
#                 'kenapasih': 'kenapa sih',
#                 '300rebu': '300 ribu',
#                 'tai': '',
#                 'gapernah': 'tidak pernah',
#                 'gedhe': 'gede',
#                 'sok2an': 'berlagak',
#                 'mbanding2ke': 'membandingkan',
#                 'sg': '',
#                 'anak2': 'anak-anak',
#                 'berubah2': 'berubah-ubah',
#                 'mks': 'masuk',
#                 'univ': 'universitas',
#                 'hny': 'hanya',
#                 'kececkek': 'ke cekik',
#                 'kyknya': 'kayaknya',
#                 'anjaay': '',
#                 'cawe2': '',
#                 'gajithr': 'gaji thr',
#                 'gedung2': 'gedung-gedung',
#                 'dlltapi': 'dan lain-lain tapi',
#                 'nasak2': 'masak-masak',
#                 'pgn': 'pengen',
#                 'bagi2': 'bagi-bagi',
#                 'tgl': 'tanggal',
#                 'nnti': 'nanti',
#                 'ibukku': 'ibu aku',
#                 'iur': 'iuran',
#                 'loo': 'loh',
#                 '1jp': '1 jam pelajaran',
#                 '30rb': '30 ribu',
#                 '1jam': '1 jam',
#                 '1bln': '1 bulan',
#                 '20jp': '20 jam pelajar',
#                 '5jpkejelasan': '5 jam pelajaran kejelasan',
#                 '5jam': '5 jam',
#                 '10-20': '10 sampai 20',
#                 'ahhh': 'ah',
#                 'abt': 'about',
#                 'betbakti': 'berbakti',
#                 'rp': 'rupiah',
#                 'rbkurang': 'ribu kurang',
#                 'njing': '',
#                 'jelas2': 'jelas-jelas',
#                 'honorerjgn': 'honorer jangan',
#                 'pejabaaat': 'penjabat',
#                 'honorere': 'honorer',
#                 'mbz': 'mbak',
#                 'drpd': 'daripada',
#                 'bgtt': 'banget',
#                 '2-3': '2 sampai 3',
#                 'kelean': 'kalian',
#                 'benerr': 'benar',
#                 'woww': 'kaget',
#                 'amit2': 'amit-amit',
#                 'sehat2': 'sehat-sehat',
#                 'mbulet': 'bulat',
#                 'yup': 'ya',
#                 '250-300k': '250 sampai 300 ribu',
#                 '125-150k': '125 sampai 150 ribu',
#                 'grobak': 'gerobak',
#                 '350rb': '350 ribu',
#                 'skrg2': 'sekarang-sekarang',
#                 'rp150': 'rupiah 150',
#                 'ank': 'anak',
#                 'bngt': 'banget',
#                 'apa2': 'apa-apa',
#                 'udah2': 'udah-udah',
#                 'yaagedenya': 'ya gedenya',
#                 'sih -': 'sih',
#                 'duhh': 'aduh',
#                 '20thn': '20 tahun',
#                 'nad1em': 'nadiem',
#                 'bgtttt': 'banget',
#                 'seringkali': 'sering kali',
#                 'gpp': 'gak apa',
#                 'insyaallah': 'insya allah',
#                 'spt': 'seperti',
#                 'prihatin': 'perihatin',
#                 'akal2an': 'akal-akalan',
#                 'fak': '',
#                 'gov': '',
#                 'cape': 'capek',
#                 's': '',
#                 'lngsng': 'langsung',
#                 'ibuk': 'ibu',
#                 'gatega': 'tidak tega',
#                 'tidk': 'tidak',
#                 'sbg': 'sebagai',
#                 'sono': 'sana',
#                 'nasib2': 'nasib-nasib',
#                 'yahh': 'yah',
#                 'gaa': 'tidak',
#                 'kdg': 'kadang',
#                 '3-6': '3 sampai 6',
#                 'gosah': 'tidak usah',
#                 'dbwh': 'dibawah',
#                 'smg': 'semoga',
#                 'mjd': 'mejadi'
#                 }

import re

# Dictionary of replacements
replacements = {'krn': 'karena',
                'blm': 'belum',
                'hrs': 'harus',
                'bkn': 'bukan',
                'yg': 'yang',
                'ny': 'ya',
                'dr': 'dari',
                'jd': 'jadi',
                'bsbs': 'bisa',
                'mrk': 'mereka',
                'msh': 'masih',
                'hrsnya': 'harus',
                'sdngkan': 'sedangkan',
                'lu': 'kamu',
                'loe': 'kamu',
                'lo': 'kamu',
                'gw': 'aku',
                'bgt': 'banget',
                'byr': 'bayar',
                'thn': 'tahun',
                'boro²': 'boro-boro',
                'hehe': 'tertawa',
                'pdhl': 'padahal',
                'semangatt':'semangat',
                'bpk': 'bapak',
                'tp': 'tapi',
                'aje': 'saja',
                'aja': 'saja',
                'ngabis2in': 'ngabisin',
                'indo': 'indonesia',
                'ngga': 'tidak',
                'nggak': 'tidak',
                'rp500': 'rupiah 500',
                'gmn': 'gimana',
                'nyuri2': 'mencuri',
                '1th': '1 tahun',
                '2jt': '2 juta',
                'kyk':' kaya',
                'kalo': 'kalau',
                'gaada': 'tidak ada',
                'yaallah': 'ya allah',
                '15jt': '15 juta',
                'tuk': 'untuk',
                '300k': '300 ribu',
                'tu': 'itu',
                'pgnnya': 'mau',
                '50k': '50 ribu',
                'ga': 'tidak',
                'gk': 'tidak',
                'murid2': 'murid-murid',
                'bjirr': '',
                'klo': 'kalau',
                'dgn': 'dengan',
                'yaaa': 'ya',
                'tmn': 'teman',
                '100k': '100 ribu',
                '600k': '600 ribu',
                'skrg': 'sekarang',
                'udh': 'sudah',
                'bnr': 'benar',
                'gak': 'tidak',
                'liat': 'lihat',
                'yaa': 'ya',
                'klao': 'kalau',
                'ganyampe': 'tidak sampai',
                'mamak': 'ibu',
                'nggk': 'tidak',
                '300rb': '300 ribu',
                'bener2': 'benar-benar',
                'klw': ' kalau',
                'kl': 'kalau',
                'wkwk':' tertawa',
                'jgn': 'jangan',
                'setiap-': 'setiap',
                'wkwkw': 'tertawa',
                '100ribu': '100 ribu',
                'jjur': 'jujur',
                'it': 'itu',
                'dpe': 'dapat',
                'skolah': 'sekolah',
                'dptnya': 'dapatnya',
                'ssuai': 'sesuai',
                'lbih': 'lebih',
                'tptnya': 'tepatnya',
                'dg': 'dengan',
                'rata2': 'rata-rata',
                '1jt': '1 juta',
                '800rb': '800 ribu',
                '600rb': '600 ribu',
                'samaratakan': 'sama rata',
                '500-1jt': '500 sampai 1 juta',
                'gue': 'aku',
                'trs': 'terus',
                'rata²': 'rata-rata',
                'maap': 'maaf',
                'emg': 'emang',
                'polll': 'banget',
                'trus': 'terus',
                'byk': 'banyak',
                '2th': '2 tahun',
                'ketidakadilam': 'tidak adil',
                'tmen': 'teman',
                'jg': 'juga',
                'bengsin': 'bensin',
                'knapa': 'kenapa',
                'njirrrr': '',
                'gata': 'gatau',
                'dll': 'dan lain-lain',
                'ekekek': 'tertawa',
                'emang': 'memang',
                'udah': 'sudah',
                'splitbill': 'split bill',
                'km': 'kamu',
                'bjrot': '',
                'gadibayar': 'tidak dibayar',
                'pns/p3k': 'pns atau p3k',
                'pokoktpg': 'pokok tpg',
                'dikantorob': 'dikantor ob',
                '6jt': '6 juta',
                '5jt': '5 juta',
                '200k': '200 ribu',
                'aj': 'saja',
                'sm': 'sama',
                'gj': 'gaji',
                'ngr': 'negara',
                'yaaaa': 'ya',
                '100k/bulan': '100 ribu per bulan',
                '150k': '150 ribu',
                'kontrak/tdk': 'kotrak atau tidak',
                'skrng': 'sekarang',
                'bnyk': 'banyak',
                'dibanding2in': 'dibanding-banding',
                'buruh2': 'buruh-buruh',
                'prcuma': 'percuma',
                'w': '',
                'g': '',
                'jdi': 'jadi',
                'mak': 'ibu',
                '300-800rb/bln': '300 sampai 800 ribu per bulan',
                'emng': 'emang',
                'swasta2': 'swasta-swasta',
                'jt': 'juta',
                '800k': '800 ribu',
                'dsb': 'dan sebagainya',
                '6jam': '6 jam',
                '60k': '60 ribu',
                '500rb': '500 ribu',
                'maknya': 'makanya',
                'cma': 'cuma',
                'wkwkwk': 'tertawa',
                'krna': 'karena',
                'poll': 'banget',
                'engga': 'tidak',
                'apalgi': 'apa lagi',
                'sekolah2': 'sekolah-sekolah',
                'guru2': 'guru-guru',
                '3bulan': '3 bulan',
                'berbulan2': 'berbulan-bulan',
                'gausah': 'tidak usah',
                'orang2': 'orang-orang',
                'sj': 'saja',
                'sy': 'saya',
                'bs': 'bisa',
                'dpt': 'dapat',
                'mmang': 'memang',
                'plg': 'paling',
                'rb': 'ribu',
                'bln': 'bulan',
                'dpt': 'dapat',
                'org': 'orang',
                'njir': '',
                'buanyakkk': 'banyak',
                '250k': '250 ribu',
                'jtan': 'jutaan',
                'bpk/ibu': 'bapak ibu',
                'bhkan': 'bahkan',
                '300rb/bulan': '300 ribu per bulan',
                'riil': 'real',
                '500-800k': '500-800 ribu',
                '50-100k': '50-100 ribu',
                'd': 'di',
                'pnsskrng': 'pns sekarang',
                'ngk': 'tidak',
                '12th': '12 tahun',
                '8jt': '8 juta',
                'sertivikasi': 'sertifikasi',
                'apalagi': 'apa lagi',
                '400k/3bln ': '400 per 3 bulan',
                'dh': 'sudah',
                'adany': 'adanya',
                'brp': 'berapa',
                'nderr': 'nder',
                'jgnkan': 'jangankan',
                'geede': 'gede',
                'gajitunjangannya': 'gaji tunjangannya',
                'ibun': 'ibu',
                'dpet': 'dapat',
                'ketrimanya': 'keterimanya',
                'taun': 'tahun',
                '500k': '500 ribu',
                'mommy': 'mother',
                '1jt/bulan': '1 juta per bulan',
                'bhs': 'bahasa',
                'th': 'tahun',
                '8rb': '8 ribu',
                '200rban': '200 ribuan',
                'lbh': 'lebih',
                'dri': 'dari',
                '2jutaan': '2 jutaan',
                'stafsus2': 'staf khusus',
                'gt': 'gitu',
                'knp': 'kenapa',
                '200-300k': '200 sampai 300 ribu',
                'dlu': 'dulu',
                'aolg': '',
                'skolah2': 'sekolah-sekolah',
                'bjir': '',
                '700/800/bln': '700 sampai 800 bulan',
                'temen2': 'teman-teman',
                'cukup2': 'cukup-cukup',
                'sihhh': 'sih',
                'jtaan': 'jutaan',
                'oon': '',
                'itutuh': 'itu',
                'smpe': 'sampai',
                'sekali2': 'sekali-sekali',
                'nyap2': 'sapa-sapa',
                'jir': '',
                'liat2': 'liat-liat',
                'kemarin2': 'kemarin-kemarin',
                'bisa2': 'bisa-bisa',
                'lg': 'lagi',
                'sgt': 'sangat',
                'wlp': 'walaupun',
                'twit': 'tweet',
                'guru²': 'guru-guru',
                'cm': 'cuma',
                'ma': 'sama',
                'plosok': 'pelosok',
                'kcil': 'kecil',
                'mrk2': 'mereka-mereka',
                'n': '',
                'bwt': 'buat',
                'murid2nya': 'muridnya',
                'kbnykn': 'kebanyakan',
                'ckp': 'cukup',
                'fokusny': 'fokusnya',
                'srtifikasi': 'sertifikasi',
                'sminar': 'seminar',
                'pnting': 'penting',
                'ja': 'aja',
                'gada': 'tidak ada',
                'guru²': 'guru-guru',
                'liet': 'liat',
                'orang²': 'orang-orang',
                'lunya': 'kamunya',
                'ko': 'kok',
                'krponakan': 'keponakan',
                'gajitunjangan': 'gaji tunjangan',
                'anying': '',
                'wkkwkwkw': '',
                '700k': '700 ribu',
                'pemerintah2': 'pemerintah-pemerintah',
                'guru²': 'guru-guru',
                'sik': 'si',
                'kota2': 'kota-kota',
                '500ish': '500 ih',
                'sgt': 'sangat',
                'lg': 'lagi',
                'manaaa': 'mana',
                'pny': 'punya',
                'noh': 'itu',
                'rebu': 'ribu',
                '3jtan': '3 jutaan',
                '5jtan': '5 jutaan',
                'buzzerp': 'buzzer',
                'goblok': '',
                'duduk2': 'duduk-duduk',
                'staff': 'staf',
                'gajiii': 'gaji',
                'tdk': 'tidak',
                'betullll': 'betul',
                'aplg': 'apa lagi',
                'ttp': 'tetap',
                'daridulu': 'dari dulu',
                'masalag': 'masalah',
                '3jt': '3 juta',
                'bwah':'bawah',
                'jkw': 'jokowi',
                '3jt-': '3 juta',
                'utk': 'untuk',
                'politiksementara': 'politik sementara',
                '450rb': '450 ribu',
                'mirisss': 'miris',
                '25ribu': '25 ribu',
                'jml': 'jumlah',
                'rp1500000': 'rupiah 1500000',
                'rp2000000': 'rupiah 2000000',
                'rp300000': 'rupiah 300000',
                'rp1000000': 'rupiah 1000000',
                'kek': 'kaya',
                'mlm': 'malam',
                'ap': 'apa',
                'bajingan': '',
                'woii': 'teriak',
                'honorerrr': 'honorer',
                'baru2': 'baru-baru',
                'manusiawimenuju': 'manusiawi menuju',
                'gila2an': 'gila-gilaan',
                'honorerviralin': 'honorer viralin',
                'dtg': 'datang',
                '20-30jt': '20 sampai 30 juta',
                'é déwé': 'dewe',
                'aq': 'aku',
                'wkt': 'waktu',
                'sdgkan': 'sedangkan',
                'tsb': 'tersebut',
                'unt': 'untuk',
                'trima': 'terima',
                'nyahmmmm': 'nya',
                'cari2': 'cari-cari',
                'bosssqq': 'bos',
                'gwe': 'aku',
                'brhrp': 'berharap',
                'y': 'ya',
                'boss': 'bos',
                'parttime': 'part time',
                'kbutuhan': 'kebutuhan',
                'sndiri': 'sendiri',
                'sihh': 'sih',
                'ma': 'sama',
                'leus': 'lexus',
                'ug': 'juga',
                'jadio': 'jadi',
                'rebu': 'ribu',
                'sama2': 'sama-sama',
                '200-300rb': '200 sampai 300 ribu',
                'tolonh': 'tolong',
                'donk': 'dong',
                'pmrintah': 'pemerintah',
                'blum': 'belum',
                'mo': 'mau',
                'tsnyw': 'tsnya',
                'embel2': 'embel-embel',
                'honorerengga': 'honorer enggan',
                'pokoktunjangan': 'pokok tunjangan',
                '4jt': '4 juta',
                'stlh': 'setelah',
                'tmbahan': 'tambahan',
                'oiyah': 'oh iya',
                '3jt': '3 juta',
                'sehari²': 'sehari-hari',
                'vidronya': 'videonya',
                'bapa': 'bapak',
                'ape': 'apa',
                'mongkin': 'mungkin',
                'ndiri': 'sendiri',
                'gapake': 'tidak pakai',
                'yanggede': 'yang gede',
                'klu': 'kalau',
                'lgi': 'lagi',
                'woooy': 'teriak',
                'sngt': 'sangat',
                'iiia': 'ia',
                'rb/bulan': 'ribu per bulan',
                'main2': 'main-main',
                'manaaa': 'mana',
                'gedeee': 'gede',
                'gua': 'aku',
                'haaa': 'kaget',
                'ape': 'apa',
                'mmg': 'memang',
                'pinjolpertama': 'pinjol pertama',
                '20ribu': '20 ribu',
                '250rebu': '250 ribu',
                'hahahahha': 'tertawa',
                'gamau': 'tidak mau',
                'idup': 'hidup',
                '6bln': '6 bulan',
                '3bln': '3 bulan',
                'skr': 'sekarang',
                'hey':'menyapa',
                '200-an': '200 an',
                'iyaa': 'iya',
                'tetep': 'tetap',
                'nyimbang': 'sumbang',
                'nder': 'sender',
                'deket': 'dekat',
                'gtu': 'gitu',
                'ckup': 'cukup',
                'kuli': 'kuliah',
                'dongg': 'dong',
                'temen': 'teman',
                'bhw': 'bahwa',
                'ortu': 'orang tua',
                'orgtua': 'orang tua',
                'gengss': 'geng',
                'sbrapa': 'seberapa',
                'sattt': '',
                'gtu': 'gitu',
                'kdd': 'kadang',
                'kd': 'kadang',
                'tpi': 'tapi',
                'susahada': 'susah ada',
                'blio': 'beliau',
                'surih': 'suruh',
                'yak': 'ya',
                'udeh': 'sudah',
                '44jt': '44 juta',
                '150rb': '150 ribu',
                'rp20': 'rupiah 20',
                'sbg': 'sebagai',
                'alloh': 'allah',
                '44jt8': '44 juta 8',
                '352jt': '352 juta',
                'gweh': 'aku',
                '19th': '19 tahun',
                'mauuuu': 'mau',
                'ajg': '',
                'awowkwk': 'tertawa',
                'beuhh': 'aduh',
                'ironic': 'ironi',
                'skitaran': 'sekitaran',
                'bln': 'bulan',
                'rata2': 'rata-rata',
                '8jm': '8 jam',
                'hr': 'hari',
                'anjggg': '',
                'anjirrr': '',
                'cmn': 'cuma',
                '200rb': '200 ribu',
                '500rb': '500 ribu',
                'mggu': 'minggu',
                'mumet2': 'mumet-mumet',
                'tpi': 'tapi',
                'yaampun': 'ya ampun',
                '2-4jt': '2 sampai 4 juta',
                'rmh': 'rumah',
                'gedong': 'gedung',
                'brngkt': 'berangkat',
                'krja': 'kerja',
                'sragam': 'seragam',
                'sbnrnya': 'sebenarnya',
                'bjirrrr': '',
                '400rb': '400 ribu',
                'dlm': 'dalam',
                'dl': 'dulu',
                'ujung2nya': 'ujungnya',
                'ntu': 'itu',
                '160juta': '160 juta',
                '300k': '300 ribu',
                'kepsek': 'kepala sosial',
                'apasih': 'apa sih',
                'coy': 'teman',
                'listrikair': 'listrik air',
                '170rb': '170 ribu',
                '348rb': '348 ribu',
                '10kg': '10 kilo',
                'sehari2': 'sehari-hari',
                'bbrp': 'beberapa',
                'anu': 'itu',
                'cwe': 'wanita',
                'anjirr': '',
                'prndapat': 'pendapat',
                'bjirrr': '',
                'kudu': 'harus',
                '8juta': '8 juta',
                'heheh': 'tertawa',
                'heheheh': 'tertawa',
                '250-400k': '250 sampai 400 ribu',
                'wkkwkw': 'tertawa',
                'ka': 'kakak',
                '500rban': '500 ribuan',
                '38jt': '38 juta',
                '48k': '48 ribu',
                'okok': 'oke',
                'ok': 'oke',
                '24jt': '24 juta',
                'ngehe': '',
                'l': '',
                'susaaaaah': 'susah',
                '600rb': '600 ribu',
                'gatau': 'tidak tahu',
                '800ribu': '800 ribu',
                'pd': 'pada',
                'enak2': 'enak-enak',
                'gapapa': 'tidak apa',
                'awokwokwok': 'tertawa',
                'baik2': 'baik-baik',
                'trmsuk': 'termasuk',
                'kdg': 'kadang',
                'mskipun': 'meskipun',
                'kdng': 'kadang',
                'dikityang': 'dikit yang',
                'dech': 'deh',
                'ver': 'ber',
                'rb': 'ribu',
                'jp': 'jam pelajaran',
                'kkak': 'kakak',
                'pdhal': 'padahal',
                'leha2': 'leha-leha',
                'hari2': 'hari-hari',
                'ky': 'kaya',
                'brooh': 'teman',
                '500k': '500 ribu',
                'samsek': 'sama sekali',
                'abcde': '',
                'bareng2': 'bareng-bareng',
                'nakes2': 'nakes-nakes',
                'beda2': 'beda-beda',
                'mirip2': 'mirip-mirip',
                'org2': 'orang-orang',
                'msii': 'misi',
                'shat': 'sehat',
                'sdah': 'sudah',
                'padti': 'pasti',
                'ks': 'kasih',
                'nnti': 'nanti',
                'coy': 'teman',
                'duh': 'aduh',
                'pakkkk': 'pak',
                'ktmu': 'ketemu',
                'ashdjdklsla': '',
                'sehari2': 'sehari-hari',
                '600khibah': '600 khibah',
                '1kalo': '1 kalau',
                '2kalau': '2 kalau',
                'sklh': 'sekolah',
                'sklah': 'sekolah',
                'jrg': 'jarang',
                'ntar': 'nanti',
                'skali': 'sekali',
                'bgitu': 'begitu',
                'kyapa': 'kaya apa',
                'soh': 'sih',
                'qt': 'kita',
                'bacot': '',
                'pmdapat': 'pendapat',
                'mlhat': 'melihat',
                'mmng': 'memang',
                'hal2': 'hal-hal',
                'mmbuat': 'membuat',
                'salah2in': 'salahin',
                'ehh': 'eh',
                'nuih': 'nih',
                'kampung2': 'kampung-kampung',
                'mw': 'mau',
                '25jt': '25 juta',
                'anak2nya': 'anaknya',
                '400-600rb': '400 sampai 600 ribu',
                '300rb-1jt': '300 sampai 1 juta',
                'tmpt': 'tempat',
                'hahah': 'tertawa',
                'jkt': 'jakarta',
                'berpuluh2': 'berpuluh-puluh',
                '300rebu': '300 ribu',
                'sbgian': 'sebagian',
                '1usd16rb': '1 dollar 16 ribu',
                'tdl': 'tidak',
                'bbrp': 'beberapa',
                'kecil2': 'kecil-kecil',
                'hadeuh': 'haduh',
                'sepong': '',
                'jdi2an': 'jadian',
                'bru': 'baru',
                'pke': 'pakai',
                'ngebacot2': '',
                'permen2kontol': '',
                'permen2heh': 'permen meyapa',
                'jing': '',
                'bcara': 'bicara',
                'permen2': 'manis-manis',
                'ngentot': '',
                'dbaju': 'di baju',
                'selesein': 'selesaikan',
                'ksejahteraan': 'kesejahteraan',
                'gbecus': 'tidak becus',
                'anjingaturan': 'aturan',
                'berduitmikir': 'berduit mikir',
                'naek': 'naik',
                'laennya': 'lainnya',
                'yth': 'yang terhormat',
                'ehh': 'eh',
                'kmu': 'kamu',
                'dkk': 'dan kawan kawan',
                'kputsn': 'keputusan',
                'btuh': 'butuh',
                'sbyk': 'sebanyak',
                'jga': 'juga',
                'owi': 'jokowi',
                'macet2': 'macet-macet',
                'bagi2': 'bagi-bagi',
                'e': '',
                'kenapasih': 'kenapa sih',
                '300rebu': '300 ribu',
                'tai': '',
                'gapernah': 'tidak pernah',
                'gedhe': 'gede',
                'sok2an': 'berlagak',
                'mbanding2ke': 'membandingkan',
                'sg': '',
                'anak2': 'anak-anak',
                'berubah2': 'berubah-ubah',
                'mks': 'masuk',
                'univ': 'universitas',
                'hny': 'hanya',
                'kececkek': 'ke cekik',
                'kyknya': 'kayaknya',
                'anjaay': '',
                'cawe2': '',
                'gajithr': 'gaji thr',
                'gedung2': 'gedung-gedung',
                'dlltapi': 'dan lain-lain tapi',
                'nasak2': 'masak-masak',
                'pgn': 'pengen',
                'bagi2': 'bagi-bagi',
                'tgl': 'tanggal',
                'nnti': 'nanti',
                'ibukku': 'ibu aku',
                'iur': 'iuran',
                'loo': 'loh',
                '1jp': '1 jam pelajaran',
                '30rb': '30 ribu',
                '1jam': '1 jam',
                '1bln': '1 bulan',
                '20jp': '20 jam pelajar',
                '5jpkejelasan': '5 jam pelajaran kejelasan',
                '5jam': '5 jam',
                '10-20': '10 sampai 20',
                'ahhh': 'ah',
                'abt': 'about',
                'betbakti': 'berbakti',
                'rp': 'rupiah',
                'rbkurang': 'ribu kurang',
                'njing': '',
                'jelas2': 'jelas-jelas',
                'honorerjgn': 'honorer jangan',
                'pejabaaat': 'penjabat',
                'honorere': 'honorer',
                'mbz': 'mbak',
                'drpd': 'daripada',
                'bgtt': 'banget',
                '2-3': '2 sampai 3',
                'kelean': 'kalian',
                'benerr': 'benar',
                'woww': 'kaget',
                'amit2': 'amit-amit',
                'sehat2': 'sehat-sehat',
                'mbulet': 'bulat',
                'yup': 'ya',
                '250-300k': '250 sampai 300 ribu',
                '125-150k': '125 sampai 150 ribu',
                'grobak': 'gerobak',
                '350rb': '350 ribu',
                'skrg2': 'sekarang-sekarang',
                'rp150': 'rupiah 150',
                'ank': 'anak',
                'bngt': 'banget',
                'apa2': 'apa-apa',
                'udah2': 'sudah-sudah',
                'yaagedenya': 'ya gedenya',
                'sih -': 'sih',
                'duhh': 'aduh',
                '20thn': '20 tahun',
                'nad1em': 'nadiem',
                'bgtttt': 'banget',
                'seringkali': 'sering kali',
                'gpp': 'tidak apa',
                'insyaallah': 'insya allah',
                'spt': 'seperti',
                'prihatin': 'perihatin',
                'akal2an': 'akal-akalan',
                'fak': '',
                'gov': '',
                'cape': 'capek',
                's': '',
                'lngsng': 'langsung',
                'ibuk': 'ibu',
                'gatega': 'tidak tega',
                'tidk': 'tidak',
                'sbg': 'sebagai',
                'sono': 'sana',
                'nasib2': 'nasib-nasib',
                'yahh': 'yah',
                'gaa': 'tidak',
                'kdg': 'kadang',
                '3-6': '3 sampai 6',
                'gosah': 'tidak usah',
                'dbwh': 'dibawah',
                'smg': 'semoga',
                'mjd': 'mejadi'
                }

# Membuat pola ekspresi reguler dengan menggabungkan kunci dengan '|'
pattern = re.compile(r'\b(' + '|'.join(re.escape(key) for key in replacements.keys()) + r')\b')

# Tentukan fungsi untuk melakukan penggantian menggunakan regex
def normalisasi(text):
    return pattern.sub(lambda x: replacements[x.group()], text)