"""Rename Tweet_url to tweet_url

Revision ID: 461e10f34f62
Revises: 9fcead63fd70
Create Date: 2024-05-18 16:12:12.294730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461e10f34f62'
down_revision = '9fcead63fd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preprocess_guru', 'Tweet_url', new_column_name='tweet_url', type_=sa.String(length=255))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preprocess_guru', 'tweet_url', new_column_name='Tweet_url', type_=sa.String(length=255))
    # ### end Alembic commands ###
