"""migrate fix twet url

Revision ID: 9fcead63fd70
Revises: f024d6ccbfd6
Create Date: 2024-05-18 15:38:36.904433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fcead63fd70'
down_revision = 'f024d6ccbfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocess_guru', schema=None) as batch_op:
        batch_op.alter_column('Tweet_url', new_column_name='tweet_url', type_=sa.String(length=255))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocess_guru', schema=None) as batch_op:
        batch_op.alter_column('tweet_url', new_column_name='Tweet_url', type_=sa.String(length=255))

    # ### end Alembic commands ###
